#!/bin/bash

# This script is intended to be sourced.
#
# Attempts to define `OVERSION` (Odoo version) by prioritizing the following methods:
# - `-o` option: If present, removes `-o` and its value from arguments
# - Regex match: Extracts version from the first argument, if applicable
# - `GLOBAL_OVERSION` variable: Uses if previously defined
# - External script (`sv` by default): If the "(s)elect (v)ersion" script exists,
#   it is executed to determine the Odoo version
#   - Script name can be customized with `SV_SCRIPT_NAME`
#   - All arguments are passed to the script
# - Fallback: Uses default version `master`, or `FALLBACK_OVERSION` if specified
#
# Enable detailed output by setting `DEBUG`.


version_rg="(master|(saas-)?[0-9]{2}\.[0-9])"

extract_version() {
  echo "$1" | grep -oE "$version_rg"
}

extract_version_strict() {
  echo "$1" | grep -oE "^$version_rg\$"
}

log() {
  if [[ $DEBUG -eq 1 ]]; then
    echo "[DEBUG $(basename "${BASH_SOURCE[0]}")] $*"
  fi
}

filtered_args=()

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -o)
      version_from_option="$2"
      shift 2
      ;;
    *)
      filtered_args+=("$1")
      shift
      ;;
  esac
done

set -- "${filtered_args[@]}"

script_name=${SV_SCRIPT_NAME:-"sv"}
log "Script name: $script_name"

log "First arg: $1"
version_from_arg=$(extract_version "$1")

if [ -n "$version_from_option" ]; then
  log "Version defined thanks to option -o"
  OVERSION=$version_from_option
elif [ -n "$version_from_arg" ]; then
  log "Version defined thanks to first arg"
  OVERSION=$version_from_arg
elif [ -n "$GLOBAL_OVERSION" ]; then
  log "Version defined thanks to global version"
  OVERSION=$GLOBAL_OVERSION
elif command -v "$script_name" >/dev/null 2>&1; then
  log "Version defined thanks to script $script_name"
  OVERSION=$($script_name "$@")
else
  log "Version defined thanks to fallback"
  version=${FALLBACK_OVERSION:-"master"}
  OVERSION="$version"
fi

log "Result before check: $OVERSION"
OVERSION=$(extract_version_strict "$OVERSION") # final check

log "Final result: $OVERSION"
if [ -z "$OVERSION" ]; then
  echo "No version found!" >&2
  exit 1
fi
