#!/bin/bash

set -e

version="${1:-15.0}"
source_path="$HOME/src/all/.idea/runConfigurations"
target_path="$HOME/src/$version/.idea/runConfigurations"
mkdir -p "$target_path"

# Detect the Python version installed in the target venv
py_version=$("$HOME/odoo-env/$version/bin/python3" -c \
  "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "3")

for file in "$source_path"/*.xml; do
  filename=$(basename "$file")
  target="$target_path/$filename"
  cp "$file" "$target"
  sed -i \
    -e "s|name=\"all\"|name=\"$version\"|g" \
    -e "s|odoo-env/Xenv|odoo-env/$version|g" \
    -e "s|Python [0-9.]* (Xenv)|Python $py_version ($version)|g" \
    -e "s|-c \$USER_HOME\$/.odoorc|-c \$USER_HOME\$/src/$version/.odoorc|g" \
    "$target"
done

echo "[$version] Run configurations updated (Python $py_version)."
