#!/bin/bash

source _set_ovariables

delete_db=true
with_demo=false

while getopts ":nD" o; do
  case "${o}" in
    n)
      delete_db=false
      shift
      ;;
    D)
      with_demo=true
      shift
      ;;
    *)
      echo "Illegal option" && exit 1
      ;;
  esac
done

version_ge_19() {
  [[ "$1" == "master" ]] && return 0
  local major; major=$(echo "$1" | grep -oE '^[0-9]+')
  [[ "$major" -ge 19 ]]
}

db=$(getdb -o "$OVERSION")
version="$OVERSION"
killodoo

if [ "$delete_db" = true ]
then
  dropdb --if-exists "$db"
  rm -rf "$HOME/.local/share/Odoo/filestore/$db"
fi

# because odoorc is relative
demo_flag=""
if [ "$with_demo" = true ]; then
  if version_ge_19 "$version"; then
    demo_flag="--with-demo"
  else
    demo_flag="--without-demo=False"
  fi
fi

if [ -f "$ODOO_SRC_PATH/$version/.odoorc" ]; then
  odoorc="$ODOO_SRC_PATH/$version/.odoorc"
else
  odoorc="$HOME/.odoorc"
fi
cd "$ODOO_SRC_PATH/$version" && "$ODOO_ENV_PATH/$version/bin/python" "$ODOO_SRC_PATH/$version/odoo/odoo-bin" -c "$odoorc" --stop-after-init -i $@ $demo_flag

if [ "$delete_db" = true ]
then
  psql -d $db -c "update ir_cron set active=false;"
  psql -d $db -c "insert into ir_config_parameter(key,value) values ('database.expiration_date','2998-05-07 13:16:50');"
fi

savedb init
