#!/bin/bash

set -e

ODOO_ENV_PATH="${ODOO_ENV_PATH:-$HOME/odoo-env}"
available=$(ls -1 "$ODOO_ENV_PATH" | grep -E '^(master|(saas-)?[0-9]{2}\.[0-9])$')
versions=${*:-$available}

for version in $versions
do
  b $version -I accountant,l10n_be,account_peppol,c_base
done


