#!/bin/bash

set -e
# set -x

ODOO_SRC_PATH="${ODOO_SRC_PATH:-$HOME/src}"
ODOO_ENV_PATH="${ODOO_ENV_PATH:-$HOME/odoo-env}"
available=$(ls -1 "$ODOO_ENV_PATH" | grep -E '^(master|(saas-)?[0-9]{2}\.[0-9])$')
versions=${*:-$available}

function update_repo {
  repo=$1

  function log {
    echo "[$repo] $1"
  }

  cd "$ODOO_SRC_PATH"/master/"$repo"

  log "Fetching $versions..."
  git fetch -q origin $versions

  log "Updating each branch..."
  for version in $versions
  do
    update_version "$repo" "$version" &
  done

  wait
  log "Done"
}

function update_version {
  repo=$1
  version=$2

  cd "$ODOO_SRC_PATH"/"$version"/"$repo"

  current_branch=$(git branch --show-current)
  git checkout -q "$version"
  git rebase --autostash origin/"$version"
  git checkout -q "$current_branch"
}

update_repo "odoo" &
update_repo "enterprise" &

wait

notify-send "oupdate" "Done"
