#!/bin/bash

set -e
# set -x

available=$(ls -1 "$HOME/odoo-env" | grep -E '^(master|(saas-)?[0-9]{2}\.[0-9])$')
versions=${*:-$available}

function update_repo {
  repo=$1

  function log {
    echo "[$repo] $1"
  }

  cd "$HOME"/src/master/"$repo"

  log "Fetching $versions..."
  git fetch -q origin $versions

  log "Updating each branch..."
  for version in $versions
  do
    update_version "$repo" "$version" &
  done

  wait
  log "Done"
}

function update_version {
  repo=$1
  version=$2

  cd "$HOME"/src/"$version"/"$repo"

  current_branch=$(git branch --show-current)
  git checkout -q "$version"
  git rebase --autostash origin/"$version"
  git checkout -q "$current_branch"
}

update_repo "odoo" &
update_repo "enterprise" &

wait

notify-send "oupdate" "Done"
